export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GROUP_ADD_SUCCESS = "GROUP_ADD_SUCCESS";
export const GROUP_ADD_FAILURE = "GROUP_ADD_FAILURE";
export const GROUP_GET_SUCCESS = "GROUP_GET_SUCCESS";
export const GROUP_GET_FAILURE = "GROUP_GET_FAILURE";
export const ADD_EXP_SUCCESS = "ADD_EXP_SUCCESS";
export const ADD_EXP_FAILURE = "ADD_EXP_FAILURE";
export const SINGLE_GROUP_GET_SUCCESS = "SINGLE_GROUP_GET_SUCCESS";
export const SINGLE_GROUP_GET_FAILURE = "SINGLE_GROUP_GET_FAILURE";
export const ARCH_GROUP_SUCCESS = "ARCH_GROUP_SUCCESS";
export const ARCH_GROUP_FAILURE = "ARCH_GROUP_FAILURE";
export const ARCH_EXP_SUCCESS = "ARCH_EXP_SUCCESS";
export const ARCH_EXP_FAILURE = "ARCH_EXP_FAILURE";

export const ACTIVITY_GET_FAILURE = "ACTIVITY_GET_FAILURE";
export const ACTIVITY_GET_SUCCESS = "ACTIVITY_GET_SUCCESS";

export const CLEAR_DEBTS_SUCCESS = "CLEAR_DEBTS_SUCCESS";
export const CLEAR_DEBTS_FAILURE = "CLEAR_DEBTS_FAILURE";

export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS";
export const DELETE_EXPENSE_FAILURE = "DELETE_EXPENSE_FAILURE";

export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_FAILURE = "ADD_MEMBER_FAILURE";

